# Generated by Django 5.0.1 on 2024-01-13 16:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('payment_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('BRADESCO', 'Bradesco'), ('C6', 'C6'), ('INTER', 'Inter'), ('ITAU', 'Itaú'), ('NUBANK', 'NuBank'), ('SANTANDER', 'Santander')], max_length=20, verbose_name='Nome da Instituição')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Saldo')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(blank=True, null=True, upload_to='img_institution', verbose_name='Imagem da Instituição')),
            ],
        ),
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=200)),
                ('value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('installments', models.SmallIntegerField(choices=[(1, '1x'), (2, '2x'), (3, '3x'), (4, '4x'), (5, '5x'), (6, '6x'), (7, '7x'), (8, '8x'), (9, '9x'), (10, '10x'), (11, '11x'), (12, '12x')])),
                ('current_installment', models.SmallIntegerField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='finance.card')),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='finance.institution'),
        ),
    ]
